git pull
echo Delete old container...
docker rm -f surveycon
docker image rm surveyimg:latest
echo Build new container...
docker build -t surveyimg .
echo Run new container...
docker run -dit --name surveycon -p 80:80 surveyimg